final Map<String, Map<String, String>> jurusanDetails = {
  'Sastra': {
    'desc': 'Jurusan ini mempelajari bahasa, sastra, dan budaya. Cocok bagi kamu yang menyukai karya sastra, bahasa asing, dan kajian budaya.',
    'ciri': 'Kreatif, analitis, peka terhadap keindahan bahasa, dan tertarik pada literatur.',
    'peluang': 'Editor, Penerjemah, Penulis, Kritikus Sastra',
    'image': 'assets/banner_sastra.jpg',
  },
  'Jurnalistik': {
    'desc': 'Jurusan ini fokus pada pengumpulan, pengolahan, dan penyampaian informasi. Cocok bagi kamu yang suka menulis dan melaporkan fakta.',
    'ciri': 'Kritis, teliti, komunikatif, dan tanggap terhadap isu terkini.',
    'peluang': 'Reporter, Editor, Penulis Berita, Jurnalis Multimedia',
    'image': 'assets/banner_jurnalistik.jpg',
  },
  'Komunikasi': {
    'desc': 'Jurusan ini mempelajari teknik komunikasi massa, hubungan masyarakat, dan media. Cocok bagi kamu yang ingin bekerja di dunia media atau kehumasan.',
    'ciri': 'Kreatif, komunikatif, analitis, dan pandai berbicara.',
    'peluang': 'Public Relations, Presenter, Content Creator, Media Planner',
    'image': 'assets/banner_komunikasi.jpg',
  },
  'Psikologi': {
    'desc': 'Jurusan ini mempelajari perilaku manusia dan proses mental. Cocok bagi kamu yang tertarik memahami kepribadian dan dinamika psikologis.',
    'ciri': 'Empatik, analitis, suka membantu orang lain, dan pandai mendengarkan.',
    'peluang': 'Psikolog, Konselor, HRD, Terapis',
    'image': 'assets/banner_psikologi.jpg',
  },
  'Pendidikan Bahasa': {
    'desc': 'Jurusan ini mengajarkan metode mengajar bahasa dan literatur. Cocok bagi kamu yang suka mengajar dan mendalami bahasa.',
    'ciri': 'Sabar, komunikatif, suka belajar bahasa, dan pandai mengajar.',
    'peluang': 'Guru Bahasa, Dosen, Penerjemah, Editor',
    'image': 'assets/banner_pendidikan.jpg',
  },
  'Hukum ': {
    'desc': 'Jurusan ini mempelajari sistem hukum dan peraturan. Cocok bagi kamu yang kritis, logis, dan ingin memperjuangkan keadilan.',
    'ciri': 'Kritis, berintegritas, teliti, dan punya kemampuan analisis yang baik.',
    'peluang': 'Pengacara, Notaris, Jaksa, Konsultan Hukum',
    'image': 'assets/banner_hukum.jpg',
  },
  'Sosiologi': {
    'desc': 'Jurusan ini mempelajari masyarakat, hubungan sosial, dan perubahan sosial.',
    'ciri': 'Kritis, analitis, peka terhadap isu sosial, dan suka mengamati interaksi masyarakat.',
    'peluang': 'Peneliti Sosial, Konsultan Kebijakan, Tenaga Ahli Pemerintahan',
    'image': 'assets/banner_sosiologi.jpg',
  },
  'Linguistik': {
    'desc': 'Jurusan ini fokus pada struktur bahasa dan fonologi. Cocok bagi kamu yang ingin mendalami ilmu bahasa secara mendalam.',
    'ciri': 'Teliti, analitis, tertarik pada bahasa dan dialek.',
    'peluang': 'Linguist, Ahli Bahasa, Penerjemah, Dosen',
    'image': 'assets/banner_linguistik.jpg',
  },
  'Antropologi': {
    'desc': 'Jurusan ini mempelajari budaya, tradisi, dan perilaku manusia dari sudut pandang sosial dan budaya.',
    'ciri': 'Observatif, peka budaya, suka penelitian lapangan.',
    'peluang': 'Peneliti Budaya, Ahli Antropologi, Konsultan Sosial',
    'image': 'assets/banner_antropologi.jpg',
  },
  'Sejarah': {
    'desc': 'Jurusan ini mempelajari peristiwa masa lalu dan dampaknya pada masa kini.',
    'ciri': 'Teliti, suka membaca dan meneliti, peka terhadap kronologi.',
    'peluang': 'Sejarawan, Arsiparis, Guru Sejarah, Kurator Museum',
    'image': 'assets/banner_sejarah.jpg',
  },
  'Pariwisata': {
    'desc': 'Jurusan ini mempelajari industri pariwisata, perhotelan, dan manajemen destinasi wisata.',
    'ciri': 'Ramah, suka berinteraksi, tertarik pada kebudayaan dan pelayanan.',
    'peluang': 'Manajer Hotel, Pemandu Wisata, Event Organizer',
    'image': 'assets/banner_pariwisata.jpg',
  },
  'Kesejahteraan Sosial': {
    'desc': 'Jurusan ini mempelajari upaya meningkatkan kualitas hidup masyarakat melalui kebijakan sosial.',
    'ciri': 'Empatik, peduli sosial, mampu bekerja dalam tim.',
    'peluang': 'Pekerja Sosial, Konsultan Kebijakan Sosial, Staf LSM',
    'image': 'assets/banner_kesejahteraan.jpg',
  },
  'Kimia': {
    'desc': 'Jurusan ini mempelajari sifat, struktur, dan perubahan materi. Cocok bagi kamu yang tertarik dengan eksperimen dan analisis kimia.',
    'ciri': 'Teliti, logis, suka eksperimen, dan analitis.',
    'peluang': 'Ahli Kimia, Peneliti, Analis Laboratorium, Teknisi Industri Kimia',
    'image': 'assets/banner_kimia.jpg',
  },
  'Biologi': {
    'desc': 'Jurusan ini mempelajari kehidupan makhluk hidup. Cocok bagi kamu yang tertarik pada ekosistem, hewan, tumbuhan, dan mikroorganisme.',
    'ciri': 'Observatif, analitis, tertarik pada alam, dan suka penelitian.',
    'peluang': 'Biolog, Ahli Ekologi, Teknisi Laboratorium, Guru Biologi',
    'image': 'assets/banner_biologi.jpg',
  },
  'Kedokteran': {
    'desc': 'Jurusan ini mempelajari ilmu kesehatan dan penyakit manusia. Cocok bagi kamu yang ingin menjadi dokter atau tenaga medis.',
    'ciri': 'Empatik, teliti, disiplin, dan punya daya tahan tinggi.',
    'peluang': 'Dokter Umum, Dokter Spesialis, Peneliti Medis',
    'image': 'assets/banner_kedokteran.jpg',
  },
  'Farmasi': {
    'desc': 'Jurusan ini mempelajari obat-obatan dan penggunaannya. Cocok bagi kamu yang tertarik di bidang kesehatan dan farmasi.',
    'ciri': 'Teliti, logis, suka ilmu kimia, dan paham kesehatan.',
    'peluang': 'Apoteker, Analis Farmasi, Ahli Formulasi',
    'image': 'assets/banner_farmasi.jpg',
  },
  'Fisika': {
    'desc': 'Jurusan ini mempelajari fenomena alam dan hukum fisika. Cocok bagi kamu yang suka hitungan dan eksperimen.',
    'ciri': 'Logis, matematis, suka eksperimen dan analisis data.',
    'peluang': 'Fisikiawan, Analis Data, Ahli Instrumentasi',
    'image': 'assets/banner_fisika.jpg',
  },
  'Teknik Elektro': {
    'desc': 'Jurusan ini mempelajari kelistrikan dan elektronika. Cocok bagi kamu yang tertarik dengan rangkaian listrik dan teknologi elektronik.',
    'ciri': 'Teknis, suka eksperimen, logis, dan inovatif.',
    'peluang': 'Engineer Listrik, Ahli Robotik, Teknisi Elektronika',
    'image': 'assets/banner_elektro.jpg',
  },
  'Teknik Mesin': {
    'desc': 'Jurusan ini mempelajari desain dan pembuatan mesin. Cocok bagi kamu yang suka teknik mekanik dan permesinan.',
    'ciri': 'Kreatif, teknis, suka inovasi dan perakitan mesin.',
    'peluang': 'Engineer Mesin, Teknisi Mekanik, Desainer Produk',
    'image': 'assets/banner_mesin.jpg',
  },
  'Geografi': {
    'desc': 'Jurusan ini mempelajari fenomena alam dan interaksi manusia dengan lingkungannya. Cocok bagi kamu yang tertarik mempelajari bumi dan pengelolaan lingkungan.',
    'ciri': 'Observatif, analitis, suka bekerja di lapangan.',
    'peluang': 'Geografer, Ahli Tata Ruang, Analis Data Lingkungan',
    'image': 'assets/banner_geografi.jpg',
  },
  'Geologi': {
    'desc': 'Jurusan ini mempelajari struktur, komposisi, dan dinamika bumi. Cocok bagi kamu yang suka penelitian lapangan dan eksplorasi sumber daya alam.',
    'ciri': 'Teliti, suka riset lapangan, dan tertarik pada batuan serta mineral.',
    'peluang': 'Ahli Geologi, Peneliti Geoteknik, Insinyur Pertambangan',
    'image': 'assets/banner_geologi.jpg',
  },
  'Teknik Pertambangan': {
    'desc': 'Jurusan ini mempelajari teknik eksplorasi dan pengelolaan sumber daya tambang. Cocok bagi kamu yang ingin bekerja di industri pertambangan.',
    'ciri': 'Teknis, analitis, suka bekerja di lapangan.',
    'peluang': 'Ahli Tambang, Insinyur Eksplorasi, Manajer Produksi Tambang',
    'image': 'assets/banner_tambang.jpg',
  },
  'Keperawatan': {
    'desc': 'Jurusan ini mempelajari teknik keperawatan dan perawatan pasien. Cocok bagi kamu yang empati dan ingin membantu sesama.',
    'ciri': 'Empatik, sabar, teliti, dan punya daya tahan tinggi.',
    'peluang': 'Perawat, Perawat Anestesi, Perawat Kesehatan Masyarakat',
    'image': 'assets/banner_keperawatan.jpg',
  },
  'Fisioterapi': {
    'desc': 'Jurusan ini mempelajari teknik rehabilitasi fisik dan terapi gerak. Cocok bagi kamu yang tertarik membantu pemulihan pasien.',
    'ciri': 'Teliti, sabar, suka membantu, dan terampil dalam terapi gerak.',
    'peluang': 'Fisioterapis, Terapis Rehabilitasi, Konsultan Kesehatan',
    'image': 'assets/banner_fisioterapi.jpg',
  },
  'Meteorologi': {
    'desc': 'Jurusan ini mempelajari cuaca, iklim, dan fenomena atmosfer. Cocok bagi kamu yang tertarik pada perubahan cuaca dan klimatologi.',
    'ciri': 'Analitis, observatif, suka riset data cuaca.',
    'peluang': 'Ahli Meteorologi, Klimatolog, Staf BMKG',
    'image': 'assets/banner_meteorologi.jpg',
  },
   'Akuntansi': {
    'desc': 'Jurusan ini mempelajari pencatatan keuangan, laporan keuangan, dan audit. Cocok bagi kamu yang teliti dan suka perhitungan.',
    'ciri': 'Teliti, logis, analitis, dan cermat dalam menghitung.',
    'peluang': 'Akuntan, Auditor, Konsultan Keuangan, Manajer Keuangan',
    'image': 'assets/banner_akuntansi.jpg',
  },
  'Ekonomi': {
    'desc': 'Jurusan ini mempelajari teori ekonomi, keuangan, dan kebijakan ekonomi. Cocok bagi kamu yang tertarik pada analisis ekonomi.',
    'ciri': 'Kritis, analitis, suka data statistik dan ekonomi.',
    'peluang': 'Ekonom, Analis Ekonomi, Konsultan Ekonomi',
    'image': 'assets/banner_ekonomi.jpg',
  },
  'Keuangan': {
    'desc': 'Jurusan ini fokus pada manajemen keuangan, investasi, dan risiko. Cocok bagi kamu yang ingin bekerja di bidang perbankan atau keuangan.',
    'ciri': 'Teliti, strategis, pandai mengelola anggaran.',
    'peluang': 'Financial Analyst, Manajer Investasi, Banker',
    'image': 'assets/banner_keuangan.jpg',
  },
  'Manajemen Pemasaran': {
    'desc': 'Jurusan ini mempelajari strategi pemasaran, branding, dan promosi. Cocok bagi kamu yang kreatif dan suka berinteraksi.',
    'ciri': 'Kreatif, komunikatif, pandai negosiasi, dan strategis.',
    'peluang': 'Marketing Manager, Brand Strategist, Digital Marketer',
    'image': 'assets/banner_pemasaran.jpg',
  },
  'Bisnis Digital': {
    'desc': 'Jurusan ini menggabungkan ilmu bisnis dan teknologi digital. Cocok bagi kamu yang ingin mendalami bisnis online dan e-commerce.',
    'ciri': 'Inovatif, adaptif, melek teknologi, dan strategis.',
    'peluang': 'E-commerce Specialist, Digital Business Analyst, Startup Founder',
    'image': 'assets/banner_bisnis_digital.jpg',
  },
  'Manajemen Logistik': {
    'desc': 'Jurusan ini mempelajari pengelolaan distribusi barang dan manajemen rantai pasok. Cocok bagi kamu yang tertarik pada efisiensi operasional.',
    'ciri': 'Teliti, strategis, pandai mengatur logistik.',
    'peluang': 'Logistics Manager, Supply Chain Analyst, Procurement Officer',
    'image': 'assets/banner_logistik.jpg',
  },
  'Supply Chain Management': {
    'desc': 'Jurusan ini fokus pada manajemen rantai pasok dan efisiensi distribusi. Cocok bagi kamu yang ingin bekerja di bidang produksi dan distribusi.',
    'ciri': 'Analitis, terorganisir, pandai mengatur arus barang.',
    'peluang': 'Supply Chain Manager, Operational Planner, Procurement Specialist',
    'image': 'assets/banner_supply_chain.jpg',
  },
  'Manajemen': {
    'desc': 'Jurusan ini mempelajari strategi organisasi, kepemimpinan, dan pengambilan keputusan. Cocok bagi kamu yang punya jiwa pemimpin.',
    'ciri': 'Kepemimpinan, strategis, pandai mengatur tim.',
    'peluang': 'Manajer Proyek, Manajer SDM, Konsultan Bisnis',
    'image': 'assets/banner_manajemen.jpg',
  },
  'Kewirausahaan': {
    'desc': 'Jurusan ini mempelajari cara memulai dan mengelola usaha. Cocok bagi kamu yang ingin menjadi pengusaha.',
    'ciri': 'Inovatif, kreatif, berani mengambil risiko.',
    'peluang': 'Entrepreneur, Business Developer, Konsultan Usaha',
    'image': 'assets/banner_kewirausahaan.jpg',
  },
  'Statistika': {
    'desc': 'Jurusan ini mempelajari teknik pengolahan dan analisis data. Cocok bagi kamu yang suka angka dan data.',
    'ciri': 'Teliti, analitis, suka menghitung dan mengolah data.',
    'peluang': 'Statistikawan, Data Analyst, Aktuaris',
    'image': 'assets/banner_statistika.jpg',
  },
  'Desain Grafis': {
    'desc': 'Jurusan ini mempelajari teknik desain visual, ilustrasi, dan pembuatan grafis digital. Cocok bagi kamu yang kreatif dan suka menggambar.',
    'ciri': 'Kreatif, inovatif, teliti dalam detail visual.',
    'peluang': 'Desainer Grafis, Illustrator, Art Director',
    'image': 'assets/banner_desain_grafis.jpg',
  },
  'Arsitektur': {
    'desc': 'Jurusan ini mempelajari perancangan bangunan dan tata ruang. Cocok bagi kamu yang suka menggambar dan merancang konstruksi.',
    'ciri': 'Kreatif, teliti, terstruktur dalam berpikir.',
    'peluang': 'Arsitek, Desainer Interior, Urban Planner',
    'image': 'assets/banner_arsitektur.jpg',
  },
  'Seni Rupa': {
    'desc': 'Jurusan ini mempelajari seni visual, lukisan, dan patung. Cocok bagi kamu yang punya bakat seni dan kreativitas tinggi.',
    'ciri': 'Ekspresif, kreatif, peka terhadap estetika.',
    'peluang': 'Pelukis, Seniman Rupa, Kurator Seni',
    'image': 'assets/banner_seni_rupa.jpg',
  },
  'Animasi': {
    'desc': 'Jurusan ini mempelajari teknik animasi digital dan produksi film animasi. Cocok bagi kamu yang suka menggambar dan membuat animasi bergerak.',
    'ciri': 'Kreatif, tekun, teliti dalam pergerakan visual.',
    'peluang': 'Animator, Motion Graphic Designer, Visual Effects Artist',
    'image': 'assets/banner_animasi.jpg',
  },
  'Desain Komunikasi Visual': {
    'desc': 'Jurusan ini mempelajari teknik visualisasi pesan melalui grafis dan media interaktif. Cocok bagi kamu yang suka desain grafis dan branding.',
    'ciri': 'Inovatif, komunikatif, pandai mengolah visual.',
    'peluang': 'Creative Director, Visual Designer, Brand Strategist',
    'image': 'assets/banner_dkv.jpg',
  },
  'Desain Interior': {
    'desc': 'Jurusan ini mempelajari tata ruang dalam bangunan untuk menciptakan estetika dan fungsionalitas. Cocok bagi kamu yang suka mendekorasi ruang.',
    'ciri': 'Kreatif, teliti, terstruktur, peka terhadap estetika.',
    'peluang': 'Desainer Interior, Konsultan Dekorasi, Visual Merchandiser',
    'image': 'assets/banner_interior.jpg',
  },
  'Sinematografi': {
    'desc': 'Jurusan ini mempelajari teknik pengambilan gambar, editing video, dan produksi film. Cocok bagi kamu yang tertarik di dunia perfilman.',
    'ciri': 'Kreatif, visual, terampil dalam teknik kamera.',
    'peluang': 'Sinematografer, Video Editor, Sutradara',
    'image': 'assets/banner_sinematografi.jpg',
  },
  'Seni Patung': {
    'desc': 'Jurusan ini mempelajari teknik pembuatan patung dan seni tiga dimensi. Cocok bagi kamu yang tertarik pada seni rupa dan pahatan.',
    'ciri': 'Kreatif, teliti, pandai mengolah bahan.',
    'peluang': 'Pematung, Pengrajin, Seniman Rupa Tiga Dimensi',
    'image': 'assets/banner_seni_patung.jpg',
  },
  'Matematika': {
    'desc': 'Jurusan ini mempelajari teori, analisis, dan penerapan matematika. Cocok bagi kamu yang suka perhitungan dan pemecahan masalah.',
    'ciri': 'Logis, analitis, teliti, suka hitungan.',
    'peluang': 'Aktuaris, Analis Data, Peneliti Matematika',
    'image': 'assets/banner_matematika.jpg',
  },
  'Teknik Industri': {
    'desc': 'Jurusan ini mempelajari optimasi proses produksi dan manajemen sistem. Cocok bagi kamu yang tertarik pada efisiensi industri.',
    'ciri': 'Analitis, strategis, suka pemecahan masalah.',
    'peluang': 'Industrial Engineer, Production Planner, Operations Manager',
    'image': 'assets/banner_teknik_industri.jpg',
  },
  'Ilmu Komputer': {
    'desc': 'Jurusan ini fokus pada teori komputasi dan pengembangan perangkat lunak. Cocok bagi kamu yang suka pemrograman dan algoritma.',
    'ciri': 'Logis, analitis, suka pemrograman.',
    'peluang': 'Software Engineer, Data Scientist, AI Developer',
    'image': 'assets/banner_ilmu_komputer.jpg',
  },
  'Teknik Informatika': {
    'desc': 'Jurusan ini mempelajari pemrograman, jaringan, dan teknologi informasi. Cocok bagi kamu yang suka pengembangan aplikasi dan sistem.',
    'ciri': 'Teknis, logis, inovatif, teliti.',
    'peluang': 'Programmer, Web Developer, Network Engineer',
    'image': 'assets/banner_teknik_informatika.jpg',
  },
  'Data Science': {
    'desc': 'Jurusan ini mempelajari pengolahan data besar dan analisis statistik. Cocok bagi kamu yang suka menganalisis data dan membuat prediksi.',
    'ciri': 'Analitis, teliti, suka pemodelan data.',
    'peluang': 'Data Analyst, Data Scientist, Machine Learning Engineer',
    'image': 'assets/banner_data_science.jpg',
  },
  'Sistem Informasi': {
    'desc': 'Jurusan ini memadukan teknologi informasi dan manajemen bisnis. Cocok bagi kamu yang ingin memahami teknologi dan proses bisnis.',
    'ciri': 'Komunikatif, analitis, suka manajemen data.',
    'peluang': 'Business Analyst, IT Consultant, System Analyst',
    'image': 'assets/banner_sistem_informasi.jpg',
  },
  'Teknik Komputer': {
    'desc': 'Jurusan ini mempelajari perangkat keras dan integrasi sistem komputer. Cocok bagi kamu yang tertarik pada pengembangan perangkat keras.',
    'ciri': 'Teknis, inovatif, teliti dalam perancangan.',
    'peluang': 'Hardware Engineer, Embedded Systems Developer, Network Administrator',
    'image': 'assets/banner_teknik_komputer.jpg',
  },
};
